### ISSUE TITLE
希望你们的CSUL项目能和我的HCSL项目合并，以支持LoongArch架构

### ISSUE THREAD

**Issue by 4Darmygeometry** [Sci-fiBrain/CSUL#5]
现我于12月初启动支持LoongArch架构，GNU/Linux，MAC，Windows的《都市：天际线2》开源第三方启动器“HCSL”项目。今获悉你们的CSUL项目与我的HCSL项目类似，且我代码水平较浅陋，现我愿意将我的HCSL项目与你们的CSUL项目合并，并希望你们能利用龙芯开源社区的.net实现该启动器在龙芯3A6000上的适配，让龙芯3A6000平台也能启动《都市：天际线2》，谢谢。
附仓库及相关图片：
仓库：https://github.com/4Darmygeometry/HCSL
相关图片：
![HCSL](https://github.com/Sci-fiBrain/CSUL/assets/87938880/ecf4067a-0abe-469b-8714-1a403141565c)
![龙芯 net](https://github.com/Sci-fiBrain/CSUL/assets/87938880/1b641392-8101-42a8-898e-5e02e5e2c6c9)

**Comment by SuperYYT** [comment]
由于本启动器创作者为非计算机专业的大学生，代码能力有限，所以难以胜任也缺乏足够的时间用以支持这两个项目的合并。

当然，我们真切地希望你的项目能做得越来越好，让天际线社区更加繁荣~

**Comment by 4Darmygeometry** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 4Darmygeometry** [comment]
我也是非计算机专业的大学生，现大三，电子商务专业。

**Comment by 4Darmygeometry** [comment]
我的项目将转为CSUL启动器在龙芯平台上的适配。现《我的世界》的第三方启动器HMCL同时支持Windows、Mac、Linux平台，且适配龙芯LoongArch架构，而贵程序员的CSUL启动器仅有Windows版，我觉得有些不妥。我愿意在闲暇时间贡献微薄之力，以共同完成CSUL启动器在龙芯3A6000平台下的适配。

**Comment by SuperYYT** [comment]
> 我的项目将转为CSUL启动器在龙芯平台上的适配。现《我的世界》的第三方启动器HMCL同时支持Windows、Mac、Linux平台，且适配龙芯LoongArch架构，而贵程序员的CSUL启动器仅有Windows版，我觉得有些不妥。我愿意在闲暇时间贡献微薄之力，以共同完成CSUL启动器在龙芯3A6000平台下的适配。

感谢你的认可和贡献精神，也欢迎你的pull request~
